stages:
- build_and_push
- deploy_pipeline

variables:
  MS_NAME: gcr-adservice
  MS_VERSION: v0.8.1


build_and_push:
  stage: build_and_push
  script:
    - echo "Building docker image $MS_NAME:$MS_VERSION and pushing to ECR"

trigger_deploy_pipeline:
  stage: deploy_pipeline
  trigger:
    project: jaweriaaslam317/online-botique-gitops
    branch: main
    strategy: depend