apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  labels:
    app: nexus
spec:
  project: default
  source:
    repoURL: https://jaweriaaslam@bitbucket.org/kubernetes-id/nexus.git
    targetRevision: master
    path: nexus/nexus-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true