apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.49.0
          securityContext:
            runAsUser: 200
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
          - name: INSTALL4J_ADD_VM_PARAMS
            value: |-
              -Xms2703M -Xmx2703M
              -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap
              -Djava.util.prefs.userRoot=/nexus-data/javaprefs
          - name: NEXUS_SECURITY_RANDOMPASSWORD
            value: "true"
          volumeMounts:
            - name:  nexus-repository-manager-data
              mountPath: /nexus-data/instances
      volumes:
        - name: nexus-repository-manager-data
          persistentVolumeClaim:
            claimName: nexus-vol-claim
