#Create storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nexus-storage-class
  namespace: nexus
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: "ext4"
volumeBindingMode: WaitForFirstConsumer
