apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv-1
  namespace: nexus
spec:
  storageClassName: nexus-storage-class
  capacity:
    storage: 35Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /nexus-data
