apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-gitops
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://gitlab.com/jaweriaaslam317/online-botique-gitops.git
    path: overlays/dev
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
