---
- name: wait for the ssh connection
  hosts: all
  tasks:
    - name: wait Untill server is created
      wait_for:
        port: 22
        delay: 10
        time_out: 100
      vars:
        ansible_connection: local



- name: Install node and npm on the server
  hosts: all
  tasks:
    - name: update the repo and cache
      apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
    - name: Install npm and nodejs
      apt:
        pkg:
        - npm
        - nodejs

- name: Create a non root userfor application
  hosts: all
  task:
    - name: create a user
      user:
      name: jaweria
      comment: work as a non root user
      group: admin

- name: deploy nodejs application
  hosts: all
  become: true
  become_user: jaweria
  tasks:
    - name: unpak the tar file
      unarchive:
        src: home/jaweria/app.1.0.0.tgz
        dest: home/jaweria
    - name: Install dependencies of the file
      npm:
        path: home/jaweria/package
    - name: start the nodejs application
      command:
        chdir: home/jaweria/package/nodejs
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}