---
- hosts: droplets
  tasks:
  - name: Install ngnix (web server)
    become: yes
    apt:
      name: nginx
      state: latest

  - name: Start web service
    become: yes
    service:
      name: nginx
      state: started

  - name: copy index.html file to target
    become: yes
    copy:
      src: index.html
      dest: /var/www/html